import { useContext } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { Spin } from "antd";
import AuthContext from "../stores/authContext";
import Layout from "../components/Layout/layout";
import Banner from "../components/Banner/banner";
import Restaurants from "../components/Restaurants/restaurants";

export default function Home() {
  const router = useRouter();

  const user = useContext(AuthContext);

  return (
    <div>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <Banner />
          <Restaurants />
        </Layout>
      </div>
    </div>
  );
}
